on:
  schedule:
    - cron:  '0 1 1 * *'  # UTC 01:00 on the first day of the Month

name: Release
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Release
        run: make release
